### ISSUE TITLE
Re-check on DOM insertion / DOM change

### ISSUE THREAD

**Issue by elgreg** [benjarwar/dial-congress#9]
Many sites inject HTML after page load. dial-congress should re-scan after new nodes are inserted.

One idea is to do this when the height of a page changes.

We could also use MutationObserver https://davidwalsh.name/mutationobserver-api

**Comment by elgreg** [comment]
I checked out MutationObserver. Of course it seems to also be triggered when inserting the actual tooltip. :) Going to look at the height idea. :)

**Comment by elgreg** [comment]
Started looking at this in https://github.com/benjarwar/dial-congress/tree/try-mutation-observer - unfortunately it just spins up my fan and never stops checking.... and subsequent scans take longer and longer? More to do. :)

**Comment by benjarwar** [comment]
Alright, so first I [merged the feature for scanning via last names first](https://github.com/benjarwar/dial-congress/pull/6) both to ```master``` and this branch. Turns out that largely solved the problem with fans spinning up and repeated, ever lengthening scans.

I then took a cue from @elgreg's TODO regarding only scanning the mutated nodes. It works pretty well, even if it's currently checking a *lot* of nodes at a time. Because it does a simple check for last names first, it's pretty damn performant. I tested on a [Twitter search for ""](https://twitter.com/search?q=bernie%20sanders&src=typd), and after some trial/error, seem to be catching the various possibilities/combinations of ```nodeType``` and ```MutationRecord```.

One thing I can't yet solve is when you hover over and the tooltip is injected, the ```body``` itself registers as a mutated node. A clumsy fix might setting a global boolean flag variable, e.g. ```tooltipsterHovered```, before the tooltipster is injected. Then checking that flag before scanning the mutated DOM elements. But gonna try to think of something sexier...

**Comment by benjarwar** [comment]
Note that the ```scan``` function now accepts a ```node``` param, so that we can pass along each mutated element during observation. I also added a hook to prevent multiple hover events being bound to a single element, by adding/checking for ```.dial-congress-mouseenter```.

**Comment by benjarwar** [comment]
This is getting closer to a more accurate way of checking whether the added/removed elements are Tooltipsters: https://github.com/benjarwar/dial-congress/commit/3e29641b309215fd27bc3f2209ebe7dbe3ded616
